export const SEARCH_FOCUS = 'SEARCH_FOCUS';
export const SEARCH_BLUR = 'SEARCH_BLUR';
export const UPDATE_TREND_LIST = 'UPDATE_TREND_LIST';
export const SEARCH_MOUSE_ENTER = 'SEARCH_MOUSE_ENTER';
export const SEARCH_MOUSE_OUT = 'SEARCH_MOUSE_OUT';